plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs8.github.io # the base hostname & protocol for your site
baseurl: /s19-matni  # the subpath of your site, e.g. "/blog"


include:
  - _pages
exclude:
  - .sass-cache
  - Gemfile
  - LICENSE
  - .bundle

course: "CS8"
qtr: "S19"
qxx: "S19"
instructor: "Matni"
quarter: "Spring 2019"
github_org_name: ucsb-cs8-s19-matni
github_org_url: https://github.com/ucsb-cs8-s19-matni

ta_list: "Chong, Shane, Brian, and Zhicheng (Reader)"
ta_list_full: "Chong Liu, Shane Masuda, Brian Young, Zhicheng Zhang (Reader)"
mentors_list: "Jacqueline Mai, Jose Recinos, Daniel Shu, Siqi Zhao, Yichen Shao"
discussion_section_times: "Mondays, 8 AM, 9 AM, 10 AM, and 11 AM (50 minutes each)"

github_url: https://github.com/ucsb-cs8/s19-matni
mentor_url: 

start_week: 1
start_date: 2019-03-31 00:00:00.00-8:00
num_weeks: 10
extra_exam_week: true
sections:

cal_dates: >
  [
    {"label":"S19 1st day of instruction", "date":"2019-04-01" },	
    {"label":"Univ Holiday", "date":"2019-05-27" },
    {"label":"S19 instruction ends", "date":"2019-06-07" },
    {"label":"S19 finals start", "date":"2019-06-10" },
    {"label":"S19 finals end", "date":"2019-06-14" },
    {"label":"S19 qtr ends", "date":"2019-06-14" }
  ]

hwk_drop_lowest: one


kramdown:
   parse_block_html: true

exclude:

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  staff:
    output: true
    permalink: /staff/:path


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: staff
    values:
     layout: staff

  - scope:
     path: ""
     type: pages
    values:
     layout: default

head_scripts:
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
